export const originalMilestoneData = [
    {color: '#AF95C2', title: 'to hire 3 people in 1 turn', text: '+2 Management Trainees.'},
    {color: '#BDB6B3', title: 'to train someone', text: '$15 discount on salaries.'},
    {color: '#98C2C9', title: 'billboard placed', text: 'No salaries for marketeers; Eternal marketing.'},
    {color: '#AF95C2', title: 'to throw away drink/food', text: 'Get a freezer that stores 10 items (drink or food).'},
    {color: '#95A968', title: 'burger produced', text: '+1 Burger Cook.'},
    {color: '#98C2C9', title: 'burger marketed', text: '+$5 for every burger sold.'},
    {color: '#AF95C2', title: 'waitress played', text: 'Each waitress +$2.'},
    {color: '#95A968', title: 'pizza produced', text: '+1 Pizza Cook.'},
    {color: '#98C2C9', title: 'pizza marketed', text: '+$5 for every pizza sold.'},
    {color: '#AF95C2', title: 'to have $20', text: 'May see bank reserve cards.'},
    {color: '#A9CB94', title: 'Errand Boy played', text: 'All buyers get +1 drink from each source.'},
    {color: '#98C2C9', title: 'drink marketed', text: '+$5 for every drink sold.'},
    {color: '#AF95C2', title: 'to have $100', text: 'Your CEO counts as CFO (+50% to cash earned). May not have CFO.'},
    {color: '#A9CB94', title: 'Cart Operator played', text: 'Buyers get range +1.'},
    {color: '#98C2C9', title: 'airplane campaign', text: 'Count +2 open slots when determining order of play.'},
    {color: '#EAA791', title: 'to lower prices', text: 'Price -$1.'},
    {color: '#BDB6B3', title: 'to pay $20 or more in salaries', text: 'May use multiple trainers on the same person.'},
    {color: '#98C2C9', title: 'radio campaign', text: 'Your radios market 2 goods per turn instead of 1.'},
    {color: '#cc0000', title: 'demand fulfulled by someone else', text: 'Range -1.'}
]
export const alternateMilestoneData = [
    {color: '#98C2C9', title: 'marketeer used', text: '$5 for every good marketed; Range -2.', maxRoundTwo: true},
    {color: '#98C2C9', title: 'marketing trainee used', text: '+1 Kitchen Trainee and +1 Errand Boy.'},
    {color: '#98C2C9', title: 'campaign manager used', text: 'May place second mailbox or billboard advertising same product and duration (only once).'},
    {color: '#98C2C9', title: 'brand manager used', text: 'May place 2 different goods on first plane. Choose priority of goods when placed.'},
    {color: '#98C2C9', title: 'brand director played', text: 'Your radio is permanent.'},
    {color: '#EAA791', title: 'burger sold', text: 'CEO always has 4 slots (regardless of reserve cards).'},
    {color: '#EAA791', title: 'pizza sold', text: 'Place radio tower on tile of sale (house) advertising pizza for two turns.'},
    {color: '#EAA791', title: 'lemonade sold', text: 'Any employee can be trained on the job, preserving color.'},
    {color: '#EAA791', title: 'beer sold', text: 'May pay salary with food or drink.'},
    {color: '#EAA791', title: 'coke sold', text: 'Get a freezer that stores 10 items (drink or food).'},
    {color: '#BDB6B3', title: 'recruiting girl played', text: 'Get a free executive vice president; Pay no salary for him.', maxRoundTwo: true},
    {color: '#BDB6B3', title: 'trainer played', text: '+1 trainer; No longer need to fire employees if broke.', maxRoundTwo: true},
    {color: '#BDB6B3', title: 'discount manager played', text: 'If you discount by -$3 or more, $100 is removed from the bank.'},
    {color: '#AF95C2', title: 'house built', text: 'May use multiple trainers on the same person.'},
    {color: '#934a34', title: 'new restaurant built', text: 'Place permanent mailbox in restaurant area.'},
    {color: '#AF95C2', title: 'waitress played', text: 'Your salaries are $3 each.'},
    {color: '#A9CB94', title: 'cart operator played', text: 'Double amount of drinks hauled by cart/truck/zeppelin.'},
    {color: '#cc0000', title: 'demand fulfulled by someone else', text: 'Range -1.'}
]
